baseURL: https://visrut7.github.io/
languageCode: en-us
theme: photophobia

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3

languages:
  en:
    title: Blog Builder
weight: 1

contentDir: content/en

sitemap:
  changefreq: daily
priority: 0.5
filename: sitemap.xml

params:
  favicon: null
site_logo: /blog-builder.png
description: Blog Builder | Just Write It!!!!!
recent_posts_number: 10

markup:
  highlight:
    style: native
